-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.cde_allocations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  cde_id uuid NOT NULL,
  type character varying NOT NULL,
  year character varying NOT NULL,
  state_code character varying,
  awarded_amount numeric NOT NULL,
  available_on_platform numeric NOT NULL,
  deployed_amount numeric DEFAULT 0,
  percentage_won numeric,
  deployment_deadline date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cde_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT cde_allocations_cde_id_fkey FOREIGN KEY (cde_id) REFERENCES public.cdes(id)
);
CREATE TABLE public.cdes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid UNIQUE,
  certification_number character varying,
  parent_organization character varying,
  year_established integer,
  primary_contact_name character varying,
  primary_contact_title character varying,
  primary_contact_email character varying,
  primary_contact_phone character varying,
  total_allocation numeric DEFAULT 0,
  remaining_allocation numeric DEFAULT 0,
  deployment_deadline date,
  min_deal_size numeric DEFAULT 1000000,
  max_deal_size numeric DEFAULT 15000000,
  small_deal_fund boolean DEFAULT false,
  service_area_type character varying DEFAULT 'national'::character varying,
  primary_states ARRAY,
  target_regions ARRAY,
  excluded_states ARRAY,
  rural_focus boolean DEFAULT false,
  urban_focus boolean DEFAULT true,
  native_american_focus boolean DEFAULT false,
  underserved_states_focus boolean DEFAULT false,
  mission_statement text,
  impact_priorities ARRAY,
  target_sectors ARRAY,
  special_focus ARRAY,
  preferred_project_types ARRAY,
  require_severely_distressed boolean DEFAULT false,
  require_qct boolean DEFAULT false,
  min_distress_score integer,
  min_project_cost numeric,
  max_project_cost numeric,
  min_jobs_created integer,
  require_community_benefits boolean DEFAULT true,
  require_shovel_ready boolean DEFAULT false,
  max_time_to_close integer,
  related_party_policy character varying DEFAULT 'case-by-case'::character varying,
  nmtc_experience boolean DEFAULT true,
  htc_experience boolean DEFAULT false,
  lihtc_experience boolean DEFAULT false,
  oz_experience boolean DEFAULT false,
  stacked_deals_preferred boolean DEFAULT false,
  total_deals_completed integer DEFAULT 0,
  total_qlici_deployed numeric DEFAULT 0,
  average_close_time integer,
  status character varying DEFAULT 'active'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_name character varying,
  CONSTRAINT cdes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cdes_merged (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  name character varying NOT NULL,
  slug character varying NOT NULL,
  year integer NOT NULL,
  allocation_type character varying DEFAULT 'federal'::character varying,
  total_allocation numeric DEFAULT 0,
  amount_finalized numeric DEFAULT 0,
  amount_remaining numeric DEFAULT 0,
  non_metro_commitment numeric DEFAULT 0,
  service_area character varying,
  service_area_type character varying,
  controlling_entity character varying,
  predominant_financing character varying,
  predominant_market text,
  innovative_activities text,
  contact_name character varying,
  contact_phone character varying,
  contact_email character varying,
  primary_states ARRAY,
  min_deal_size numeric DEFAULT 1000000,
  max_deal_size numeric DEFAULT 15000000,
  small_deal_fund boolean DEFAULT false,
  rural_focus boolean DEFAULT false,
  urban_focus boolean DEFAULT true,
  status character varying DEFAULT 'active'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  target_sectors ARRAY DEFAULT '{}'::text[],
  require_severely_distressed boolean DEFAULT false,
  min_distress_percentile integer DEFAULT 0,
  minority_focus boolean DEFAULT false,
  uts_focus boolean DEFAULT false,
  nonprofit_preferred boolean DEFAULT false,
  forprofit_accepted boolean DEFAULT true,
  owner_occupied_preferred boolean DEFAULT false,
  CONSTRAINT cdes_merged_pkey PRIMARY KEY (id)
);
CREATE TABLE public.census_tracts_geom_backup (
  geoid character varying,
  geom USER-DEFINED
);
CREATE TABLE public.closing_checklist_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_type character varying NOT NULL,
  category character varying NOT NULL,
  item_name character varying NOT NULL,
  description text,
  required boolean DEFAULT true,
  conditional_on jsonb,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT closing_checklist_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.closing_room_channels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  deal_id uuid NOT NULL,
  name text NOT NULL,
  type text NOT NULL DEFAULT 'text'::text CHECK (type = ANY (ARRAY['text'::text, 'audio'::text, 'video'::text])),
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT closing_room_channels_pkey PRIMARY KEY (id),
  CONSTRAINT closing_room_channels_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id)
);
CREATE TABLE public.closing_room_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  room_id uuid NOT NULL,
  room_type text NOT NULL DEFAULT 'text'::text,
  sender_id uuid,
  sender_name text NOT NULL,
  sender_org_id uuid,
  sender_org_name text,
  content text NOT NULL,
  file_url text,
  deleted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT closing_room_messages_pkey PRIMARY KEY (id),
  CONSTRAINT closing_room_messages_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.closing_room_channels(id),
  CONSTRAINT closing_room_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id)
);
CREATE TABLE public.closing_rooms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  deal_id uuid NOT NULL UNIQUE,
  commitment_id uuid,
  loi_id uuid,
  status character varying DEFAULT 'active'::character varying,
  target_close_date date,
  actual_close_date date,
  participants jsonb DEFAULT '[]'::jsonb,
  checklist_progress jsonb DEFAULT '{}'::jsonb,
  notes text,
  opened_at timestamp with time zone DEFAULT now(),
  closed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT closing_rooms_pkey PRIMARY KEY (id),
  CONSTRAINT closing_rooms_commitment_id_fkey FOREIGN KEY (commitment_id) REFERENCES public.commitments(id),
  CONSTRAINT closing_rooms_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id),
  CONSTRAINT closing_rooms_loi_id_fkey FOREIGN KEY (loi_id) REFERENCES public.letters_of_intent(id)
);
CREATE TABLE public.commitment_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  commitment_id uuid NOT NULL,
  from_status USER-DEFINED,
  to_status USER-DEFINED NOT NULL,
  changed_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT commitment_history_pkey PRIMARY KEY (id),
  CONSTRAINT commitment_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id),
  CONSTRAINT commitment_history_commitment_id_fkey FOREIGN KEY (commitment_id) REFERENCES public.commitments(id)
);
CREATE TABLE public.commitments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  commitment_number character varying UNIQUE,
  deal_id uuid NOT NULL,
  loi_id uuid,
  investor_id uuid NOT NULL,
  cde_id uuid,
  sponsor_id uuid NOT NULL,
  status USER-DEFINED DEFAULT 'draft'::commitment_status,
  investment_amount numeric NOT NULL,
  credit_type USER-DEFINED NOT NULL,
  credit_rate numeric,
  expected_credits numeric,
  pricing_cents_per_credit numeric,
  net_benefit_to_project numeric,
  cra_eligible boolean DEFAULT false,
  expires_at timestamp with time zone,
  target_closing_date date,
  response_deadline timestamp with time zone,
  conditions jsonb DEFAULT '[]'::jsonb,
  special_terms text,
  investor_requirements jsonb DEFAULT '{}'::jsonb,
  sponsor_accepted_at timestamp with time zone,
  sponsor_accepted_by uuid,
  cde_accepted_at timestamp with time zone,
  cde_accepted_by uuid,
  all_accepted_at timestamp with time zone,
  issued_at timestamp with time zone,
  issued_by uuid,
  rejection_reason text,
  rejected_by uuid,
  rejected_at timestamp with time zone,
  withdrawn_at timestamp with time zone,
  withdrawn_by uuid,
  withdrawn_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT commitments_pkey PRIMARY KEY (id),
  CONSTRAINT commitments_cde_accepted_by_fkey FOREIGN KEY (cde_accepted_by) REFERENCES public.users(id),
  CONSTRAINT commitments_cde_id_fkey FOREIGN KEY (cde_id) REFERENCES public.cdes(id),
  CONSTRAINT commitments_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id),
  CONSTRAINT commitments_investor_id_fkey FOREIGN KEY (investor_id) REFERENCES public.investors(id),
  CONSTRAINT commitments_issued_by_fkey FOREIGN KEY (issued_by) REFERENCES public.users(id),
  CONSTRAINT commitments_loi_id_fkey FOREIGN KEY (loi_id) REFERENCES public.letters_of_intent(id),
  CONSTRAINT commitments_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES public.users(id),
  CONSTRAINT commitments_sponsor_accepted_by_fkey FOREIGN KEY (sponsor_accepted_by) REFERENCES public.users(id),
  CONSTRAINT commitments_sponsor_id_fkey FOREIGN KEY (sponsor_id) REFERENCES public.sponsors(id),
  CONSTRAINT commitments_withdrawn_by_fkey FOREIGN KEY (withdrawn_by) REFERENCES public.users(id)
);
CREATE TABLE public.conversation_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  user_id uuid NOT NULL,
  user_name character varying,
  user_email character varying,
  organization_id uuid,
  organization_name character varying,
  organization_type character varying,
  role character varying DEFAULT 'member'::character varying CHECK (role::text = ANY (ARRAY['owner'::character varying::text, 'admin'::character varying::text, 'member'::character varying::text])),
  unread_count integer DEFAULT 0,
  last_read_at timestamp with time zone,
  joined_at timestamp with time zone DEFAULT now(),
  left_at timestamp with time zone,
  CONSTRAINT conversation_participants_pkey PRIMARY KEY (id),
  CONSTRAINT conversation_participants_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type character varying NOT NULL DEFAULT 'direct'::character varying CHECK (type::text = ANY (ARRAY['direct'::character varying::text, 'deal'::character varying::text, 'team'::character varying::text, 'group'::character varying::text])),
  deal_id uuid,
  deal_name character varying,
  name character varying,
  category character varying,
  last_message text,
  last_message_at timestamp with time zone,
  last_sender_id uuid,
  last_sender_name character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id)
);
CREATE TABLE public.dd_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  deal_id uuid NOT NULL,
  category character varying NOT NULL,
  document_id uuid,
  status character varying DEFAULT 'not_started'::character varying,
  required boolean DEFAULT false,
  required_by character varying DEFAULT 'all'::character varying,
  requested_by_id uuid,
  requested_by_org character varying,
  requested_at timestamp with time zone,
  uploaded_at timestamp with time zone,
  reviewed_at timestamp with time zone,
  reviewed_by_id uuid,
  review_notes text,
  expires_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dd_documents_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dda_metro_2025 (
  zcta character varying NOT NULL,
  cbsasub character varying,
  area_name character varying,
  population_2020 integer,
  population_in_qct integer,
  population_not_in_qct integer,
  safmr_2br numeric,
  vlil_4person integer,
  lihtc_max_rent numeric,
  sdda_ratio numeric,
  pop_over_100 integer,
  cumulative_population integer,
  cumulative_percent numeric,
  is_sdda integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dda_metro_2025_pkey PRIMARY KEY (zcta)
);
CREATE TABLE public.dda_metro_2026 (
  zcta character varying NOT NULL,
  cbsasub character varying,
  area_name character varying,
  population_2020 integer,
  population_in_qct integer,
  population_not_in_qct integer,
  safmr_2br numeric,
  vlil_4person integer,
  lihtc_max_rent numeric,
  sdda_ratio numeric,
  pop_over_100 integer,
  cumulative_population integer,
  cumulative_percent numeric,
  is_sdda integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dda_metro_2026_pkey PRIMARY KEY (zcta)
);
CREATE TABLE public.dda_nonmetro_2025 (
  county_fips character varying NOT NULL,
  cbsasub character varying,
  area_name character varying,
  population_2020 numeric,
  population_in_qct numeric,
  effective_population numeric,
  fmr_2br numeric,
  vlil_4person integer,
  lihtc_max_rent numeric,
  dda_ratio numeric,
  cumulative_population bigint,
  cumulative_percent numeric,
  is_nmdda integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dda_nonmetro_2025_pkey PRIMARY KEY (county_fips)
);
CREATE TABLE public.dda_nonmetro_2026 (
  county_fips character varying NOT NULL,
  cbsasub character varying,
  area_name character varying,
  population_2020 numeric,
  population_in_qct numeric,
  effective_population numeric,
  fmr_2br numeric,
  vlil_4person integer,
  lihtc_max_rent numeric,
  dda_ratio numeric,
  cumulative_population bigint,
  cumulative_percent numeric,
  is_nmdda integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dda_nonmetro_2026_pkey PRIMARY KEY (county_fips)
);
CREATE TABLE public.deal_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  deal_id uuid NOT NULL,
  file_url text NOT NULL,
  file_type text,
  file_name text,
  file_size integer,
  category text,
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT deal_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT deal_attachments_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id),
  CONSTRAINT deal_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.deal_checklists (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  deal_id uuid NOT NULL,
  template_id uuid NOT NULL,
  status character varying DEFAULT 'pending'::character varying,
  document_id uuid,
  notes text,
  due_date date,
  completed_at timestamp with time zone,
  completed_by uuid,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT deal_checklists_pkey PRIMARY KEY (id)
);
CREATE TABLE public.deal_matches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  deal_id uuid NOT NULL,
  cde_id uuid NOT NULL,
  score integer NOT NULL DEFAULT 0,
  match_strength character varying NOT NULL DEFAULT 'weak'::character varying,
  breakdown jsonb,
  reasons ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT deal_matches_pkey PRIMARY KEY (id),
  CONSTRAINT deal_matches_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id)
);
CREATE TABLE public.deal_media (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  deal_id uuid NOT NULL,
  media_type text NOT NULL DEFAULT 'image'::text,
  url text NOT NULL,
  file_name text,
  file_size integer,
  order integer DEFAULT 0,
  caption text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT deal_media_pkey PRIMARY KEY (id),
  CONSTRAINT deal_media_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id)
);
CREATE TABLE public.deal_relationship_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  relationship_id uuid NOT NULL,
  from_status USER-DEFINED,
  to_status USER-DEFINED NOT NULL,
  changed_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT deal_relationship_history_pkey PRIMARY KEY (id),
  CONSTRAINT deal_relationship_history_relationship_id_fkey FOREIGN KEY (relationship_id) REFERENCES public.deal_relationships(id)
);
CREATE TABLE public.deal_relationships (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  deal_id uuid NOT NULL,
  target_type character varying NOT NULL CHECK (target_type::text = ANY (ARRAY['cde'::character varying, 'investor'::character varying]::text[])),
  target_id uuid NOT NULL,
  target_org_id uuid,
  target_name character varying NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'contacted'::relationship_status,
  status_note text,
  match_score integer,
  match_strength character varying,
  match_reasons ARRAY,
  outreach_id uuid,
  loi_id uuid,
  commitment_id uuid,
  last_message text,
  last_contact_at timestamp with time zone,
  next_action text,
  next_action_due timestamp with time zone,
  requested_amount numeric,
  committed_amount numeric,
  contacted_at timestamp with time zone DEFAULT now(),
  interested_at timestamp with time zone,
  verbal_approval_at timestamp with time zone,
  loi_issued_at timestamp with time zone,
  loi_accepted_at timestamp with time zone,
  committed_at timestamp with time zone,
  closed_at timestamp with time zone,
  denied_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT deal_relationships_pkey PRIMARY KEY (id),
  CONSTRAINT deal_relationships_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id)
);
CREATE TABLE public.deals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  project_name character varying NOT NULL,
  sponsor_id uuid NOT NULL,
  sponsor_name character varying,
  programs ARRAY NOT NULL DEFAULT '{}'::program_type[],
  program_level character varying DEFAULT 'federal'::character varying,
  state_program character varying,
  address character varying,
  city character varying,
  state character varying,
  zip_code character varying,
  county character varying,
  census_tract character varying,
  latitude numeric,
  longitude numeric,
  tract_types ARRAY,
  tract_poverty_rate numeric,
  tract_median_income numeric,
  tract_unemployment numeric,
  tract_eligible boolean,
  tract_severely_distressed boolean,
  tract_classification character varying,
  project_type character varying,
  venture_type character varying,
  project_description text,
  tenant_mix text,
  total_project_cost numeric,
  nmtc_financing_requested numeric,
  financing_gap numeric,
  land_cost numeric,
  acquisition_cost numeric,
  construction_cost numeric,
  soft_costs numeric,
  contingency numeric,
  developer_fee numeric,
  financing_costs numeric,
  reserves numeric,
  equity_amount numeric,
  debt_amount numeric,
  grant_amount numeric,
  other_amount numeric,
  committed_capital_pct numeric,
  jobs_created integer,
  jobs_retained integer,
  permanent_jobs_fte numeric,
  construction_jobs_fte numeric,
  commercial_sqft integer,
  housing_units integer,
  affordable_housing_units integer,
  community_benefit text,
  site_control character varying,
  site_control_date date,
  phase_i_environmental character varying,
  zoning_approval character varying,
  building_permits character varying,
  construction_drawings character varying,
  construction_start_date date,
  projected_completion_date date,
  projected_closing_date date,
  status USER-DEFINED DEFAULT 'draft'::deal_status,
  visible boolean DEFAULT false,
  readiness_score integer DEFAULT 0,
  tier integer DEFAULT 1,
  assigned_cde_id uuid,
  assigned_cde_name character varying,
  investor_id uuid,
  investor_name character varying,
  exclusivity_agreed boolean DEFAULT false,
  exclusivity_agreed_at timestamp with time zone,
  qalicb_data jsonb DEFAULT '{}'::jsonb,
  htc_data jsonb DEFAULT '{}'::jsonb,
  intake_data jsonb DEFAULT '{}'::jsonb,
  checklist jsonb DEFAULT '{}'::jsonb,
  ai_flags ARRAY,
  scoring_breakdown jsonb,
  submitted_at timestamp with time zone,
  matched_at timestamp with time zone,
  closing_started_at timestamp with time zone,
  closed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  phase text DEFAULT 'investor'::text,
  visibility_level text DEFAULT 'market'::text,
  draft_data jsonb DEFAULT '{}'::jsonb,
  sponsor_organization_id uuid,
  CONSTRAINT deals_pkey PRIMARY KEY (id),
  CONSTRAINT deals_assigned_cde_id_fkey FOREIGN KEY (assigned_cde_id) REFERENCES public.cdes(id),
  CONSTRAINT deals_investor_id_fkey FOREIGN KEY (investor_id) REFERENCES public.investors(id),
  CONSTRAINT deals_sponsor_id_fkey FOREIGN KEY (sponsor_id) REFERENCES public.sponsors(id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid,
  deal_id uuid,
  closing_room_id uuid,
  uploaded_by uuid,
  name character varying NOT NULL,
  file_url text NOT NULL,
  file_size integer,
  mime_type character varying,
  category character varying,
  tags ARRAY,
  status USER-DEFINED DEFAULT 'pending'::document_status,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_notes text,
  version integer DEFAULT 1,
  parent_document_id uuid,
  ai_summary text,
  ai_flags ARRAY,
  content_hash character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT documents_closing_room_id_fkey FOREIGN KEY (closing_room_id) REFERENCES public.closing_rooms(id),
  CONSTRAINT documents_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id),
  CONSTRAINT documents_parent_document_id_fkey FOREIGN KEY (parent_document_id) REFERENCES public.documents(id),
  CONSTRAINT documents_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id),
  CONSTRAINT documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.historic_buildings (
  id integer NOT NULL DEFAULT nextval('historic_buildings_id_seq'::regclass),
  ref_number character varying UNIQUE,
  prefix character varying,
  property_name character varying NOT NULL,
  state character varying,
  state_abbr character varying,
  county character varying,
  city character varying,
  street_address character varying,
  address text,
  zip_code character varying,
  status character varying,
  request_type character varying,
  restricted_address boolean DEFAULT false,
  acreage numeric,
  area_of_significance text,
  category character varying,
  external_link text,
  significance_international boolean DEFAULT false,
  significance_local boolean DEFAULT false,
  significance_national boolean DEFAULT false,
  significance_not_indicated boolean DEFAULT false,
  significance_state boolean DEFAULT false,
  listed_date date,
  multiple_property_listing character varying,
  nhl_designated_date date,
  other_names text,
  park_name character varying,
  periods_of_significance character varying,
  property_id character varying,
  latitude numeric,
  longitude numeric,
  is_htc_eligible boolean DEFAULT true,
  is_nhl boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT historic_buildings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.hoa_data (
  state text,
  county text,
  tract text,
  fips11 text,
  msa23 text,
  high_opp integer,
  dda_flag integer,
  qap_flag integer,
  ct_duplicate integer,
  geoid text NOT NULL,
  CONSTRAINT hoa_data_pkey PRIMARY KEY (geoid)
);
CREATE TABLE public.investors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid UNIQUE,
  primary_contact_name character varying,
  primary_contact_email character varying,
  primary_contact_phone character varying,
  investor_type character varying,
  cra_motivated boolean DEFAULT false,
  min_investment numeric,
  max_investment numeric,
  target_credit_types ARRAY,
  target_states ARRAY,
  target_sectors ARRAY,
  total_investments integer DEFAULT 0,
  total_invested numeric DEFAULT 0,
  accredited boolean DEFAULT true,
  verified_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_name character varying,
  CONSTRAINT investors_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ledger_anchors (
  id bigint NOT NULL DEFAULT nextval('ledger_anchors_id_seq'::regclass),
  ledger_event_id bigint NOT NULL,
  anchored_hash character varying NOT NULL,
  anchor_type character varying NOT NULL,
  external_reference text,
  anchored_at timestamp with time zone DEFAULT now(),
  verified boolean DEFAULT false,
  verified_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT ledger_anchors_pkey PRIMARY KEY (id),
  CONSTRAINT ledger_anchors_ledger_event_id_fkey FOREIGN KEY (ledger_event_id) REFERENCES public.ledger_events(id)
);
CREATE TABLE public.ledger_events (
  id bigint NOT NULL DEFAULT nextval('ledger_events_id_seq'::regclass),
  event_timestamp timestamp with time zone DEFAULT now(),
  actor_type USER-DEFINED NOT NULL,
  actor_id character varying NOT NULL,
  entity_type character varying NOT NULL,
  entity_id character varying NOT NULL,
  action character varying NOT NULL,
  payload_json jsonb DEFAULT '{}'::jsonb,
  model_version character varying,
  reason_codes jsonb,
  prev_hash character varying,
  hash character varying NOT NULL,
  sig text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ledger_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ledger_verifications (
  id bigint NOT NULL DEFAULT nextval('ledger_verifications_id_seq'::regclass),
  start_event_id bigint,
  end_event_id bigint,
  events_checked integer NOT NULL,
  chain_valid boolean NOT NULL,
  signatures_valid boolean,
  anchor_matched boolean,
  issues jsonb DEFAULT '[]'::jsonb,
  requested_by character varying,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT ledger_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT ledger_verifications_end_event_id_fkey FOREIGN KEY (end_event_id) REFERENCES public.ledger_events(id),
  CONSTRAINT ledger_verifications_start_event_id_fkey FOREIGN KEY (start_event_id) REFERENCES public.ledger_events(id)
);
CREATE TABLE public.letters_of_intent (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  loi_number character varying UNIQUE,
  deal_id uuid NOT NULL,
  cde_id uuid NOT NULL,
  sponsor_id uuid NOT NULL,
  status USER-DEFINED DEFAULT 'draft'::loi_status,
  allocation_amount numeric NOT NULL,
  qlici_rate numeric,
  leverage_structure character varying DEFAULT 'standard'::character varying,
  term_years integer DEFAULT 7,
  expires_at timestamp with time zone,
  expected_closing_date date,
  sponsor_response_deadline timestamp with time zone,
  conditions jsonb DEFAULT '[]'::jsonb,
  special_terms text,
  cde_requirements jsonb DEFAULT '{}'::jsonb,
  sponsor_response_at timestamp with time zone,
  sponsor_response_notes text,
  counter_terms jsonb,
  issued_at timestamp with time zone,
  issued_by uuid,
  withdrawn_at timestamp with time zone,
  withdrawn_by uuid,
  withdrawn_reason text,
  superseded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT letters_of_intent_pkey PRIMARY KEY (id),
  CONSTRAINT letters_of_intent_cde_id_fkey FOREIGN KEY (cde_id) REFERENCES public.cdes(id),
  CONSTRAINT letters_of_intent_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id),
  CONSTRAINT letters_of_intent_issued_by_fkey FOREIGN KEY (issued_by) REFERENCES public.users(id),
  CONSTRAINT letters_of_intent_sponsor_id_fkey FOREIGN KEY (sponsor_id) REFERENCES public.sponsors(id),
  CONSTRAINT letters_of_intent_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES public.letters_of_intent(id),
  CONSTRAINT letters_of_intent_withdrawn_by_fkey FOREIGN KEY (withdrawn_by) REFERENCES public.users(id)
);
CREATE TABLE public.lihtc_qct_2025 (
  state text,
  county text,
  stcnty text,
  tract text,
  geoid character varying NOT NULL,
  split_tr text,
  qct_id text,
  metro text,
  Area_Pop text,
  cbsa text,
  cbsasub24 text,
  VLIL4_2020 text,
  VLIL4_2021 text,
  VLIL4_2022 text,
  P1 text,
  P5 text,
  H1 text,
  B17001est1_20 text,
  B17001me1_20 text,
  B17001est2_20 text,
  B17001me2_20 text,
  B19013est1_20 text,
  B19013me1_20 text,
  B17001est1_21 text,
  B17001me1_21 text,
  B17001est2_21 text,
  B17001me2_21 text,
  B19013est1_21 text,
  B19013me1_21 text,
  B17001est1_22 text,
  B17001me1_22 text,
  B17001est2_22 text,
  B17001me2_22 text,
  B19013est1_22 text,
  B19013me1_22 text,
  AvgHHSize text,
  adj_inc_lim_20 text,
  adj_inc_lim_21 text,
  adj_inc_lim_22 text,
  inc_factor_20 text,
  inc_factor_21 text,
  inc_factor_22 text,
  pov_rate_20 text,
  pov_rate_21 text,
  pov_rate_22 text,
  qct text,
  CONSTRAINT lihtc_qct_2025_pkey PRIMARY KEY (geoid)
);
CREATE TABLE public.lihtc_qct_2026 (
  geoid text NOT NULL,
  state text,
  county text,
  stcnty text,
  tract text,
  metro text,
  is_qct boolean,
  pov_rate_21 text,
  pov_rate_22 text,
  pov_rate_23 text,
  CONSTRAINT lihtc_qct_2026_pkey PRIMARY KEY (geoid)
);
CREATE TABLE public.loi_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  loi_id uuid NOT NULL,
  from_status USER-DEFINED,
  to_status USER-DEFINED NOT NULL,
  changed_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loi_history_pkey PRIMARY KEY (id),
  CONSTRAINT loi_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id),
  CONSTRAINT loi_history_loi_id_fkey FOREIGN KEY (loi_id) REFERENCES public.letters_of_intent(id)
);
CREATE TABLE public.master_tax_credit_sot (
  geoid text NOT NULL,
  geom USER-DEFINED,
  geom_simplified USER-DEFINED,
  centroid_lat double precision,
  centroid_lng double precision,
  state_fips text,
  county_fips text,
  tract_fips text,
  state_name text,
  county_name character varying,
  metro_status character varying,
  is_nmtc_eligible boolean,
  is_nmtc_high_migration boolean,
  nmtc_poverty_rate numeric,
  nmtc_mfi_percent numeric,
  nmtc_unemployment_rate numeric,
  is_severely_distressed boolean,
  is_lihtc_qct_2025 boolean,
  is_lihtc_qct_2026 boolean,
  is_oz_designated boolean,
  has_state_nmtc boolean,
  has_state_lihtc boolean,
  has_state_htc boolean,
  has_state_oz_conformity boolean,
  has_brownfield_credit boolean,
  stack_score integer,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  is_dda_2025 boolean DEFAULT false,
  is_dda_2026 boolean DEFAULT false,
  is_high_opportunity_area boolean DEFAULT false,
  high_opp_category integer DEFAULT 0,
  is_tribal_area boolean DEFAULT false,
  tribal_aian_code integer,
  is_rcap boolean DEFAULT false,
  is_acp boolean DEFAULT false,
  CONSTRAINT master_tax_credit_sot_pkey PRIMARY KEY (geoid)
);
CREATE TABLE public.match_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  deal_id uuid NOT NULL,
  sponsor_id uuid NOT NULL,
  target_type character varying NOT NULL CHECK (target_type::text = ANY (ARRAY['cde'::character varying, 'investor'::character varying]::text[])),
  target_id uuid NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'declined'::character varying, 'withdrawn'::character varying, 'expired'::character varying]::text[])),
  message text,
  responded_at timestamp with time zone,
  response_message text,
  responded_by_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '30 days'::interval),
  CONSTRAINT match_requests_pkey PRIMARY KEY (id),
  CONSTRAINT match_requests_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id),
  CONSTRAINT match_requests_sponsor_id_fkey FOREIGN KEY (sponsor_id) REFERENCES public.sponsors(id)
);
CREATE TABLE public.message_reads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  message_id uuid NOT NULL,
  user_id uuid NOT NULL,
  read_at timestamp with time zone DEFAULT now(),
  CONSTRAINT message_reads_pkey PRIMARY KEY (id),
  CONSTRAINT message_reads_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  sender_name character varying,
  sender_org character varying,
  sender_org_id uuid,
  content text NOT NULL,
  message_type character varying DEFAULT 'text'::character varying CHECK (message_type::text = ANY (ARRAY['text'::character varying::text, 'file'::character varying::text, 'system'::character varying::text, 'loi'::character varying::text, 'commitment'::character varying::text])),
  file_url text,
  file_name character varying,
  file_type character varying,
  file_size integer,
  metadata jsonb,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  is_edited boolean DEFAULT false,
  edited_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);
CREATE TABLE public.nmtc_cde_allocatees (
  id integer NOT NULL DEFAULT nextval('nmtc_cde_allocatees_id_seq'::regclass),
  name_of_allocatee text,
  year_of_award text,
  total_allocation text,
  amount_finalized text,
  amount_remaining text,
  non_metro_commitment text,
  service_area text,
  controlling_entity text,
  contact_person text,
  predominant_financing text,
  predominant_market_served text,
  innovative_activities text,
  contact_name text,
  contact_phone text,
  contact_email text,
  CONSTRAINT nmtc_cde_allocatees_pkey PRIMARY KEY (id)
);
CREATE TABLE public.nmtc_census_tracts (
  geoid text NOT NULL,
  metro_designation text,
  is_nmtc_eligible boolean,
  poverty_rate double precision,
  poverty_qualified boolean,
  mfi_percent double precision,
  mfi_qualified boolean,
  unemployment_rate double precision,
  county_code text,
  state_name text,
  county_name text,
  unemployment_ratio double precision,
  unemployment_high boolean,
  population bigint,
  CONSTRAINT nmtc_census_tracts_pkey PRIMARY KEY (geoid)
);
CREATE TABLE public.nmtc_ct_data_2025 (
  geoid character varying NOT NULL,
  metro_status character varying,
  is_non_metro boolean DEFAULT false,
  is_lic_eligible boolean DEFAULT false,
  poverty_rate numeric,
  qualifies_poverty boolean DEFAULT false,
  mfi_pct numeric,
  qualifies_mfi boolean DEFAULT false,
  unemployment_rate numeric,
  unemployment_ratio numeric,
  county_fips character varying,
  state_name character varying,
  county_name character varying,
  population integer,
  is_high_migration boolean DEFAULT false,
  is_severely_distressed boolean DEFAULT false,
  is_deeply_distressed boolean DEFAULT false,
  state_fips character varying DEFAULT "substring"((geoid)::text, 1, 2),
  tract_fips character varying DEFAULT "substring"((geoid)::text, 6, 6),
  data_source character varying DEFAULT 'CDFI Fund NMTC 2016-2020 ACS LIC 2025'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT nmtc_ct_data_2025_pkey PRIMARY KEY (geoid)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  type character varying NOT NULL,
  title character varying NOT NULL,
  message text,
  entity_type character varying,
  entity_id character varying,
  read boolean DEFAULT false,
  read_at timestamp with time zone,
  action_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.opportunity_zones_staging (
  id integer NOT NULL DEFAULT nextval('opportunity_zones_staging_id_seq'::regclass),
  OBJECTID integer,
  GEOID character varying,
  STATE character varying,
  COUNTY character varying,
  TRACT character varying,
  STUSAB character varying,
  STATE_NAME character varying,
  Shape__Area numeric,
  Shape__Length numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT opportunity_zones_staging_pkey PRIMARY KEY (id)
);
CREATE TABLE public.organization_subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  external_subscription_id character varying,
  external_subscription_item_id character varying,
  current_plan_slug character varying,
  current_status character varying,
  current_period_start timestamp without time zone,
  current_period_end timestamp without time zone,
  external_updated_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT organization_subscriptions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.poverty_data (
  state text,
  county text,
  tract text,
  msa2023 text,
  qct2023 integer,
  qct2024 integer,
  rcap2024 integer,
  acp2024 integer,
  geoid text NOT NULL,
  CONSTRAINT poverty_data_pkey PRIMARY KEY (geoid)
);
CREATE TABLE public.project_assignments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  deal_id uuid NOT NULL,
  role character varying DEFAULT 'member'::character varying,
  assigned_by uuid,
  assigned_at timestamp with time zone DEFAULT now(),
  CONSTRAINT project_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT project_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.users(id),
  CONSTRAINT project_assignments_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id),
  CONSTRAINT project_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.small_financial_institutions (
  id integer NOT NULL DEFAULT nextval('small_financial_institutions_id_seq'::regclass),
  reporting_date text,
  agency_file text,
  institution_name text,
  address text,
  city text,
  state text,
  fhfa_sfi_number text,
  rssd_id text,
  fdic_cert_number text,
  ncua_cu_number text,
  fca_inst_number text,
  CONSTRAINT small_financial_institutions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.sponsors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid UNIQUE,
  primary_contact_name character varying,
  primary_contact_email character varying,
  primary_contact_phone character varying,
  organization_type character varying,
  low_income_owned boolean,
  woman_owned boolean DEFAULT false,
  minority_owned boolean DEFAULT false,
  veteran_owned boolean DEFAULT false,
  total_projects_completed integer DEFAULT 0,
  total_project_value numeric DEFAULT 0,
  exclusivity_agreed boolean DEFAULT false,
  exclusivity_agreed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_name character varying,
  CONSTRAINT sponsors_pkey PRIMARY KEY (id)
);
CREATE TABLE public.state_fips_lookup (
  fips character varying NOT NULL,
  state_name character varying NOT NULL,
  state_abbrev character varying NOT NULL,
  CONSTRAINT state_fips_lookup_pkey PRIMARY KEY (fips)
);
CREATE TABLE public.state_tax_credit_programs_staging (
  id integer NOT NULL DEFAULT nextval('state_tax_credit_programs_staging_id_seq'::regclass),
  geoid character varying,
  state_name character varying,
  state_nmtc text,
  program_name text,
  admin_agency text,
  credit_structure text,
  state_nmtc_transferable text,
  Notes / Statutory Reference text,
  state_lihtc text,
  program_size text,
  tc_%_years text,
  refundable_transferable_stc text,
  admin_agent_lihtc text,
  state_htc text,
  tc% text,
  annual_or_per_project_cap text,
  st_htc_transferable text,
  st_htc_refundable text,
  admin_agent_sthtc text,
  oz_to_fed text,
  st_oz_tc text,
  Program Type text,
  Administering Agency_OZ text,
  brownfield_credit text,
  Credit Type text,
  Credit % / Amount text,
  Refundable / Transferable_BROWNFIELD text,
  Administering Agency text,
  Notes / Statutes text,
  Stackable With text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT state_tax_credit_programs_staging_pkey PRIMARY KEY (id)
);
CREATE TABLE public.team_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  role USER-DEFINED DEFAULT 'MEMBER'::user_role,
  title character varying,
  invited_by uuid,
  invited_at timestamp with time zone,
  accepted_at timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  invite_token character varying,
  CONSTRAINT team_members_pkey PRIMARY KEY (id),
  CONSTRAINT team_members_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id),
  CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.tract_geometries (
  geoid text,
  state_fips text,
  county_fips text,
  tract_code text,
  tract_name text,
  land_area bigint,
  water_area bigint,
  geometry USER-DEFINED,
  geometry_simplified USER-DEFINED
);
CREATE TABLE public.tribal_data (
  state text,
  county text,
  tract text,
  msa2023 text,
  aian integer,
  dts_ia integer,
  geoid text NOT NULL,
  CONSTRAINT tribal_data_pkey PRIMARY KEY (geoid)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  avatar_url text,
  role USER-DEFINED DEFAULT 'MEMBER'::user_role,
  phone character varying,
  title character varying,
  is_active boolean DEFAULT true,
  email_verified boolean DEFAULT false,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  role_type character varying CHECK (role_type::text = ANY (ARRAY['sponsor'::character varying::text, 'cde'::character varying::text, 'investor'::character varying::text])),
  organization_id uuid,
  organization_name character varying,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.zip_tract_crosswalk (
  zip text NOT NULL,
  tract text NOT NULL,
  res_ratio double precision,
  CONSTRAINT zip_tract_crosswalk_pkey PRIMARY KEY (zip, tract)
);